GreedyMusic/urls.py
__author__ = 'anuraagbasu'

from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls', namespace="music")),
]

if not settings.DEBUG:
    urlpatterns += patterns('',(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

music/urls.py
__author__ = 'anuraagbasu'

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from music import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^tracks', views.showAllTracks, name='showAllTracks'),
    url(r'^track/add', views.addTrack, name='addTrack'),
    url(r'^track/(?P<trackId>[0-9]+)/$', views.trackDetail, name='trackDetail'),
    url(r'^track/(?P<trackId>[0-9]+)/edit/$', views.trackUpdate, name='trackUpdate'),

    url(r'^genres', views.showAllGenres, name='showAllGenres'),
    url(r'^genre/add', views.addGenre, name='addGenre'),
    url(r'^genre/(?P<genreId>[0-9]+)/$', views.genreDetail, name='genreDetail'),
    url(r'^genre/(?P<genreId>[0-9]+)/edit/$', views.genreUpdate, name='genreUpdate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/models.py
__author__ = 'anuraagbasu'

from django.db import models
from datetime import datetime

class Track (models.Model):
    title = models.CharField(max_length=200)
    createDate = models.DateTimeField(default=datetime.now())
    rating = models.IntegerField(default=0)
    genres = models.ManyToManyField('Genre')
    def getRatingIterable(self):
        return range(0, self.rating)
    def getRemainingRatingiterable(self):
        return range(0, 5-self.rating)
    def getGenresAsString(self):
        genresAsString = ""
        for genre in self.genres.all():
            genresAsString = genresAsString + " | "
            genresAsString = genresAsString + genre.name

        if genresAsString!="":
            value = "[" + genresAsString[3:] + "]"
            return value
        else:
            return genresAsString


class Genre (models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=1000, blank=True)

music/forms.py
__author__ = 'anuraagbasu'

from django.db import models

class TrackForm (ModelForm):
    class Meta:
        model = Track

class GenreForm (ModelForm):
    class Meta:
        model = Genre

music/views.py
__author__ = 'anuraagbasu'

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from django.db.models import Q

from music.models import Track, Genre

def index (request):
    trackList = Track.objects.order_by('createDate')[:10]
    genreList = Genre.objects.all()[:10]
    context = dict()
    context['trackList'] = trackList
    context['genreList'] = genreList
    return render(request, "music/index.html", context)

def showAllTracks (request):
    if request.method == 'GET' and 'search' in request.GET:
        print("showing all tracks")
        searchText = request.GET['search']
        if searchText is not None and searchText != '':
            print("searchText: " + searchText)
            tracksList = Track.objects.filter(title__icontains=searchText)
            context = dict()
            context['tracksList'] = tracksList
            context['maxRating'] = range(1, 6)
            context['searchText'] = searchText
            return render(request, "music/track.list.html", context)
        else:
            tracksList = Track.objects.order_by('createDate')
            context = dict()
            context['tracksList'] = tracksList
            context['maxRating'] = range(1, 6)
            context['searchText'] = ""
            return render(request, "music/track.list.html", context)
    else:
        tracksList = Track.objects.order_by('createDate')
        context = dict()
        context['tracksList'] = tracksList
        context['maxRating'] = range(1, 6)
        context['searchText'] = ""
        return render(request, "music/track.list.html", context)


def addTrack (request):
    if request.method == "POST":
        trackTitle = request.POST.get('title')
        if trackTitle!="":
            try:
                track = Track(title=trackTitle, rating=request.POST.get('rating'), )
                track.save()
                genres = request.POST.getlist('genres')
                for genreId in genres:
                    genre = Genre.objects.get(pk=genreId)
                    track.genres.add(genre)
            except ():
                return render(request, 'music/track.add.html', {
                    'error_message': "Something aweful happened. Try again"
                })
            else:
                return HttpResponseRedirect(reverse('music:showAllTracks'))
        else:
            return render(request, 'music/track.add.html', {
                'error_message': "Can't save empty Track"
            })
    else:
        genreList = Genre.objects.all()
        context = dict()
        context['genreList'] = genreList
        return render(request, 'music/track.add.html', context)

def trackDetail (request, trackId):
    track = get_object_or_404(Track, pk=trackId)
    context = dict()
    context['track'] = track
    return render(request, "music/track.show.html", context)

def trackUpdate (request, trackId):
    if request.method == "POST":
        trackTitle = request.POST.get('title')
        if trackTitle!="":
            trackRating = request.POST.get('rating')
            try:
                Track.objects.filter(pk=trackId).update(title=trackTitle, rating=trackRating)
                track = Track.objects.get(pk=trackId)
                track.genres.clear()
                genres = request.POST.getlist('genres')
                for genreId in genres:
                    genre = Genre.objects.get(pk=genreId)
                    track.genres.add(genre)
            except () :
                return render(request, 'music/track.edit.html', {
                    'error_message': "Something aweful happened. Try again"
                })
            else:
                return HttpResponseRedirect(reverse('music:showAllTracks'))
        else:
            return render(request, 'music/track.add.html', {
                'error_message': "Can't save empty Track"
            })
    else:
        track = Track.objects.get(pk=trackId)
        genreList = Genre.objects.all()
        context = dict()
        context['track'] = track
        context['genreList'] = genreList
        return render(request, "music/track.edit.html", context)

def showAllGenres (request):
    if request.method == 'GET' and 'search' in request.GET:
        print("showing all genres")
        searchText = request.GET['search']
        if searchText is not None and searchText != '':
            print("searchText: " + searchText)
            genreList = Genre.objects.filter(name__icontains=searchText)
            context = dict()
            context['genreList'] = genreList
            context['searchText'] = searchText
            return render(request, "music/genre.list.html", context)
        else:
            genreList = Genre.objects.all()
            context = dict()
            context['genreList'] = genreList
            context['searchText'] = ""
            return render(request, "music/genre.list.html", context)
    else:
        genreList = Genre.objects.all()
        context = dict()
        context['genreList'] = genreList
        context['searchText'] = ""
        return render(request, "music/genre.list.html", context)

def addGenre (request):
    if request.method == "POST":
        genreName = request.POST.get('name')
        if genreName!="":
            try:
                genre = Genre(name=genreName, description=request.POST.get('description'))
                genre.save()
            except ():
                return render(request, 'music/genre.add.html', {
                    'error_message': "Something aweful happened"
                })
            else:
                return HttpResponseRedirect(reverse('music:showAllGenres'))
        else:
            return render(request, 'music/genre.add.html', {
                'error_message': "Can't save empty Genre"
            })
    else:
        return render(request, 'music/genre.add.html')

def genreDetail (request, genreId):
    genre = get_object_or_404(Genre, pk=genreId)
    context = dict()
    context['genre'] = genre
    return render(request, "music/genre.show.html", context)

def genreUpdate (request, genreId):
    if request.method == "POST":
        genreName = request.POST.get('name')
        if genreName!="":
            genreDescription = request.POST.get('description')
            try:
                Genre.objects.filter(pk=genreId).update(name=genreName, description=genreDescription)
            except ():
                return render(request, 'music/genre.edit.html', {
                    'error_message': "Something aweful happened. Try again"
                })
            else:
                return HttpResponseRedirect(reverse('music:showAllGenres'))
        else:
            return render(request, 'music/genre.edit.html', {
                'error_message': "Can't save empty Genre"
            })
    else:
        genre = Genre.objects.get(pk=genreId)
        context = dict()
        context['genre'] = genre
        return render(request, 'music/genre.edit.html', context)

music/templates/music/genre.add.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Add Details | Genre</h4>

    <form action="{% url 'music:addGenre' %}" method="post">
        {% csrf_token %}

        <div class="group">
            <input name="name" class="form-control" placeholder="Genre Name">
        </div>

        <div class="group">
            <textarea name="description" class="form-control" placeholder="Genre Description"></textarea>
        </div>

        <div class="group">
            <button type="submit" class="action-btn">Add Genre</button>
        </div>
    </form>

    {% if error_message %}
        <span class="info-section">
            {{ error_message }}
        </span>
    {% endif %}
</div>

music/templates/music/genre.edit.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Update Details | Genre</h4>

    <form action="{% url 'music:genreUpdate' genre.id %}" method="post">
        {% csrf_token %}

        <div class="group">
            <input name="name" class="form-control" placeholder="Genre Name" value="{{genre.name}}">
        </div>

        <div class="group">
            <textarea name="description" class="form-control" placeholder="Genre Description">{{genre.description}}</textarea>
        </div>

        <div class="group">
            <button type="submit" class="action-btn">Update Genre</button>
        </div>
    </form>

    {% if error_message %}
        <span class="info-section">
            {{ error_message }}
        </span>
    {% endif %}
</div>

music/templates/music/genre.list.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Track's Genres</h4>

    <div class="search-form">
        <form action="{% url 'music:showAllGenres' %}">
            <div class="group">
                <input name="search" class="search-control" placeholder="Search Genre" value="{{searchText}}">
            </div>

            <input type="hidden" type="submit">
        </form>
    </div>

    {% if genreList %}
    <ul>
        {% for genre in genreList %}
        <li>
            <a href="/music/genre/{{genre.id}}">{{genre.name}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No Genres added yet</p>
    {% endif %}

    <div class="action-btn">
        <a href="/music/genre/add">Add New Genre</a>
    </div>
</div>

music/templates/music/genre.show.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Genre Details</h4>

    <div class="genre-wrapper section">
        <div class="genre-name">{{genre.name}}</div>
        <div class="genre-description">{{genre.description}}</div>

        <div class="edit-icon">
            <a href="/music/genre/{{genre.id}}/edit">Edit</a>
        </div>
    </div>

    {% if genre.track_set.all %}
    <div class="track-list-section section">
        <div class="title">Tracks</div>
        <div class="track-list">
            <ul>
                {% for track in genre.track_set.all %}
                <li class="track">
                    <a href="/music/track/{{track.id}}">
                        <span class="track-title">{{track.title}}</span>

                        {% if track.getGenresAsString %}
                        <span class="genres">
                            {{ track.getGenresAsString }}
                        </span>
                        {% endif %}

                        <span class="ratings-section">
                            {% for rating in track.getRatingIterable %}
                            <span class="star completed"></span>
                            {% endfor %}

                            {% for rating in track.getRemainingRatingiterable %}
                            <span class="star"></span>
                            {% endfor %}
                        </span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
</div>

music/templates/music/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <div class="track-list-container section">
        <div class="title">Tracks</div>
        {% if trackList %}
        <ul class="track-wrapper">
            {% for track in trackList %}
            <li class="track">
                <a href="/music/track/{{track.id}}">
                    <span class="track-title">{{track.title}}</span>

                    {% if track.getGenresAsString %}
                <span class="genres">
                    {{ track.getGenresAsString }}
                </span>
                    {% endif %}

                <span class="ratings-section">
                    {% for rating in track.getRatingIterable %}
                    <span class="star completed"></span>
                    {% endfor %}

                    {% for rating in track.getRemainingRatingiterable %}
                    <span class="star"></span>
                    {% endfor %}
                </span>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="info-wrapper">
            <p>No Tracks Added Yet</p>
        </div>
        <div class="action-btn">
            <a href="/music/track/add">Add New Track</a>
        </div>
        {% endif %}

        <div class="action-btn">
            <a href="/music/tracks">View All Tracks</a>
        </div>
    </div>

    <div class="genre-list-container section">
        <div class="title">Genres</div>
        {% if genreList %}
        <ul>
            {% for genre in genreList %}
            <li>
                <a href="/music/genre/{{genre.id}}">{{genre.name}}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="info-wrapper">
            <p>No Genres Added Yet</p>
        </div>
        <div class="action-btn">
            <a href="/music/genre/add">Add New Genre</a>
        </div>
        {% endif %}

        <div class="action-btn">
            <a href="/music/genres">View All Genres</a>
        </div>
    </div>
</div>

music/templates/music/track.add.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Add Details | Track</h4>

    <form action="{% url 'music:addTrack' %}" method="post">
        {% csrf_token %}

        <div class="group">
            <input id="trackTitle" name="title" placeholder="Track Title" class="form-control">
        </div>

        <div class="group">
            <select class="form-control" name="genres" multiple="multiple">
                {% for genre in genreList %}
                <option value="{{genre.id}}">{{genre.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="group">
            <input class="form-control" name="rating" type="number" max="5" min="0" value="0">
            <span>/</span>
            <span>5</span>
        </div>

        <div class="group">
            <button type="submit" class="action-btn">Add Track</button>
        </div>
    </form>

    {% if error_message %}
        <span class="info-section">
            {{ error_message }}
        </span>
    {% endif %}
</div>

music/templates/music/track.edit.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Update Details | Track</h4>

    <form action="{% url 'music:trackUpdate' track.id %}" method="post">
        {% csrf_token %}

        <div class="group">
            <input name="title" placeholder="Track Title" class="form-control" value="{{track.title}}">
        </div>

        <div class="group">
            <select class="form-control" name="genres" multiple="multiple">
                {% for genre in genreList %}
                    {% if genre in track.genres.all %}
                    <option value="{{genre.id}}" selected>{{genre.name}}</option>
                    {% else %}
                    <option value="{{genre.id}}">{{genre.name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>

        <div class="group">
            <input class="form-control" name="rating" type="number" max="5" min="0" value="{{track.rating}}">
            <span>/</span>
            <span>5</span>
        </div>

        <div class="group">
            <button type="submit" class="action-btn">Update Track</button>
        </div>
    </form>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</div>

music/templates/music/track.list.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container track-list-container">
    <h4>Music Tracks</h4>

    <div class="search-form">
        <form action="{% url 'music:showAllTracks' %}">
            <div class="group">
                <input name="search" class="search-control" placeholder="Search Track" value="{{searchText}}">
            </div>

            <input type="hidden" type="submit">
        </form>
    </div>

    {% if tracksList %}
    <ul class="track-wrapper">
        {% for track in tracksList %}
        <li class="track">
            <a href="/music/track/{{track.id}}">
                <span class="track-title">{{track.title}}</span>

                {% if track.getGenresAsString %}
                <span class="genres">
                    {{ track.getGenresAsString }}
                </span>
                {% endif %}

                <span class="ratings-section">
                    {% for rating in track.getRatingIterable %}
                    <span class="star completed"></span>
                    {% endfor %}

                    {% for rating in track.getRemainingRatingiterable %}
                    <span class="star"></span>
                    {% endfor %}
                </span>
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="info-wrapper">
        <p>No Tracks Added Yet</p>
    </div>
    {% endif %}

    <div class="action-btn">
        <a href="/music/track/add">Add New Track</a>
    </div>
</div>

music/templates/music/track.show.html
{% load static %}
<link rel="stylesheet" href="{% static 'music/index.css' %}">

<div class="container">
    <h4>Track Details</h4>

    <div class="section track-wrapper">
        <div class="track-title">{{track.title}}</div>
        <div class="track-rating">
            <span class="label">Rating:</span>
            <span>{{track.rating}}</span>
        </div>
        <div class="track-genre">
            <span class="label">Genre:</span>

            <span class="genre">
                {% with track.genres.all|first as firstGenre %}
                <a href="/music/genre/{{firstGenre.id}}">{{firstGenre.name}}</a>
                {% endwith %}
            </span>

            {% for genre in track.genres.all %}
                {% if not forloop.first %}
                <span>,</span>
                <span class="genre">
                    <a href="/music/genre/{{genre.id}}">{{genre.name}}</a>
                </span>
                {% endif %}
            {% endfor %}
        </div>

        <div class="edit-icon">
            <a href="/music/track/{{track.id}}/edit">Edit</a>
        </div>
    </div>
</div>